-- 广告表
CREATE TABLE `ad`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '广告id',
  `title` VARCHAR(32) DEFAULT NULL COMMENT '标题',
  `img_file_name` VARCHAR(128) DEFAULT NULL COMMENT '图片文件名',
  `link` VARCHAR(512) DEFAULT NULL COMMENT '链接地址',
  `wight` INT DEFAULT NULL COMMENT '权重',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY pk_id(`id`)
)ENGINE = Innodb DEFAULT CHARSET = utf8 COMMENT = '广告表';