-- 广告表
CREATE TABLE `ad`(
  `ad_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '广告id',
  `ad_title` VARCHAR(32) DEFAULT NULL COMMENT '标题',
  `ad_img` VARCHAR(128) DEFAULT NULL COMMENT '图片文件名',
  `ad_link` VARCHAR(512) DEFAULT NULL COMMENT '链接地址',
  `ad_wight` INT DEFAULT NULL COMMENT '权重',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY pk_adid(`ad_id`)
)ENGINE = Innodb DEFAULT CHARSET = utf8 COMMENT = '广告表';